name: Java CI with Maven

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: '8'
        maven-version: '3.8.3'
    - name: Build with Maven
      run: mvn compile
      
  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Running Test
        run: mvn test
        
  Package:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.8.3'
      - name: Package
        run: mvn -D skipTests clean package
      - name: Create Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: PrinoFy
          path: target/*.jar
          
  Release:
    runs-on: ubuntu-latest
    needs: Package
    steps:
      - name: Download file Jar Artifact
        uses: actions/download-artifact@v3
        with:
          name: PrinoFy
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: PrinoFy
